name: Update Twitter Header
on:
  workflow_dispatch:
  schedule:
    - cron: '*/1 * * * *'

jobs:
  getdata:
    name: Get Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r .github/requirements.txt
      - run: python .github/header.py
        env:
          DEFAULT_BRANCH: main
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
          ACCESS_TOKEN : ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET : ${{ secrets.ACCESS_TOKEN_SECRET }}
